/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ApproverGroupObjectPageObjectPage journey");

        opaTest("Navigate to ApproverGroupObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheApproverGroupListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheApproverGroupListGenerated.onTable().iCheckRows();
            When.onTheApproverGroupListGenerated.onTable().iPressRow(0);

            Then.onTheApproverGroupObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheApproverGroupObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheApproverGroupObjectPageGenerated.iPressSectionIconTabFilterButton("GeneratedFacet1");
            Then.onTheApproverGroupObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheApproverGroupObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GroupName" });
            Then.onTheApproverGroupObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Description" });
            Then.onTheApproverGroupObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "IsActive" });
            When.onTheApproverGroupObjectPageGenerated.iPressSectionIconTabFilterButton("AssignedApprovers");
            Then.onTheApproverGroupObjectPageGenerated.iCheckSection({ section: "AssignedApprovers" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});